import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property<int> counter: 42;
    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
            font-size: 32px;
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.counter += 1;
            }
        }
     }
}